version: '3'
services:
  web:
    image: nginx:alpine  
    ports:
      - "8080:80"        
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/style.css:/usr/share/nginx/html/style.css
      - ./frontend/script.js:/usr/share/nginx/html/script.js
      - ./nginx.conf:/etc/nginx/nginx.conf

